# Generated by Django 3.2.13 on 2022-08-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscard',
            name='projectName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectscard',
            name='projectTags',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectscard',
            name='refImg',
            field=models.ImageField(default=1, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
